#!/bin/sh
#
# Copyright 2018 Skalski Embedded Technologies <contact@lukasz-skalski.com>
#
# This file is part of MZD Background Changer.
#
# MZD Background Changer is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# MZD Background Changer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with MZD Background Changer. If not, see <http://www.gnu.org/licenses/>.

bin_file="MZDBackgroundChanger"

while true; do

  # start daemon
  /tmp/$bin_file

  # check return value
  ret_value=$?

  if [ $ret_value -eq 0 ]; then
    exit 0;
  fi

  sleep 5;

done
exit 0
